### ISSUE TITLE
Support for iOS in XCODE

### ISSUE THREAD

**Issue by serek8** [sampsyo/llvm-pass-skeleton#25]
Hey, I am trying to get the skeleton work on iOS platform and I followed your README and got the Pass working on MacOS. However, when I want to set it up on iOS project in XCODE and set "Other C Flags" to "-Xclang -load -Xclang libSkeletonPass.so" on iOS project I get the following error:
```
error: unable to load plugin 'libSkeletonPass.so': 'dlopen(libSkeletonPass.so, 9): 
  Symbol not found: __ZN4llvm24DisableABIBreakingChecksE
  Referenced from:libSkeletonPass.so
  Expected in: flat namespace
 in /libSkeletonPass.so'
Command CompileC failed with a nonzero exit code 
```
Do you have any idea how to fix this? Have you tried using it with iOS?

**Comment by sampsyo** [comment]
Hello! Errors like this typically mean the pass was built against the wrong version of LLVM. Building a pass for the right version of LLVM may be tricky in this case because, presumably, Xcode’s own LLVM does not come with a CMakeLists.txt. Maybe you can consider building part of your project separately, with your own separate Clang from Homebrew or whatever, and then linking that in with the rest of your project.

**Comment by serek8** [comment]
Sounds good, I will give it a try. Thanks for your help!
